//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfzDemos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViolateInfo
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int studentID { get; set; }
        public string partment { get; set; }
        public string profession { get; set; }
        public int buildingNum { get; set; }
        public int dormNum { get; set; }
        public string reason { get; set; }
        public string time { get; set; }
    }
}
